/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fylder_ndk_demo_DemoTools */

#ifndef _Included_fylder_ndk_demo_DemoTools
#define _Included_fylder_ndk_demo_DemoTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fylder_ndk_demo_DemoTools
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fylder_ndk_demo_DemoTools_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
